apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: emp-gateway
  namespace: backend
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 8080
      name: http
      protocol: HTTP
    hosts:
    - "emp.kimdragon50.ml"
