apiVersion: v1
kind: Service
metadata:
  labels:
    app: emp-api
    service: emp-api
  name: emp-api
  namespace: backend
spec:
  ports:
    - port: 8080
      name: http
      protocol: TCP
  selector:
    app: emp-api