{
 "title": "ALL Nodes Status",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "nodegroup",
    "query": "label_values(kube_node_labels, label_eks_amazonaws_com_nodegroup)"
   },
   {
    "name": "node",
    "query": "label_values(kube_node_labels{label_eks_amazonaws_com_nodegroup =~ \"$nodegroup\"}, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "Pod Count - Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Pod Count  - Running",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_running_pod_count{instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Pod Count - Not Running",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{node=~\"$node\"}) - sum(kubelet_running_pod_count{instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1 - (sum(node_cpu_seconds_total{kubernetes_node=~\"$node\", mode=\"idle\"}) by (kubernetes_node) / sum(node_cpu_seconds_total{kubernetes_node=~\"$node\"}) by (kubernetes_node))) * 100",
     "legendFormat": "{{kubernetes_node}}-cpu-utilization"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{kubernetes_node=~\"$node\"} - node_memory_MemAvailable_bytes{kubernetes_node=~\"$node\"}) / node_memory_MemTotal_bytes{kubernetes_node=~\"$node\"} * 100",
     "legendFormat": "{{kubernetes_node}}-memory-utilization"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum (node_filesystem_size_bytes{kubernetes_node=~\"$node\"}) by (kubernetes_node) - sum (node_filesystem_free_bytes{kubernetes_node=~\"$node\"}) by (kubernetes_node)) / sum (node_filesystem_size_bytes{kubernetes_node=~\"$node\"}) by (kubernetes_node) * 100",
     "legendFormat": "{{kubernetes_node}}-disk-utilization"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{kubernetes_node=~\"$node\"}[5m]) / (1024 * 1024)) by (kubernetes_node)",
     "legendFormat": "{{kubernetes_node}}-read-bytes"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{kubernetes_node=~\"$node\"}[5m]) / (1024 * 1024)) by (kubernetes_node)",
     "legendFormat": "{{kubernetes_node}}-write-bytes"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{kubernetes_node=~\"$node\",device=~\"eth.*\"}[2m]) / (1024 * 1024)) by (kubernetes_node)",
     "legendFormat": "{{kubernetes_node}}-network-in"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{kubernetes_node=~\"$node\",device=~\"eth.*\"}[2m]) / (1024 * 1024)) by (kubernetes_node)",
     "legendFormat": "{{kubernetes_node}}-network-out"
    }
   ]
  }
 ]
}