apiVersion: v1
data:
  config.yaml: |
    istio_namespace: istio-system
    deployment:
      accessible_namespaces: ['**']
    auth:
      strategy: login
    server:
      port: 20001
      web_root: /kiali
    external_services:
      tracing:
        url: http://jaeger-query.istio-system.svc.cluster.local/jaeger
      prometheus:
        url: http://prometheus.istio-system.svc.cluster.local:9090
kind: ConfigMap
metadata:
  labels:
    app: kiali
    chart: kiali
    release: istio
  name: kiali
  namespace: istio-system