apiVersion: apps/v1
kind: Deployment
metadata:
  name: emp-api
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emp-api
  template:
    metadata:
      labels:
        app: emp-api
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nodegroup-type
                operator: In
                values:
                - BACKEND
      terminationGracePeriodSeconds: 30
      containers:
        - name: emp-api
          image: 058475846659.dkr.ecr.ap-northeast-2.amazonaws.com/backend-emp:2021-04-29_16-12-43.997
          ports:
            - containerPort: 8080
#          resources:
#            requests:
#              cpu: "30m"
#              memory: "64Mi"
#            limits:
#              cpu: "50m"
#              memory: "64Mi"