apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-api
  template:
    metadata:
      labels:
        app: web-api
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nodegroup-type
                operator: In
                values:
                - FRONTEND
      terminationGracePeriodSeconds: 30
      containers:
        - name: web-api
          image: 058475846659.dkr.ecr.ap-northeast-2.amazonaws.com/frontend-web:2021-04-29_10-58-48
          ports:
            - containerPort: 80
         resources:
           requests:
             cpu: "300m"
