apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  addonComponents:
    grafana:
      enabled: false
    istiocoredns:
      enabled: false
    tracing:
      enabled: true
    prometheus:
      enabled: true
    kiali:
      enabled: true
  components:
    egressGateways:
      - enabled: false
    ingressGateways:
      - enabled: true
    base:
      enabled: true
    citadel:
      enabled: false
    cni:
      enabled: false
    istiodRemote:
      enabled: false
    policy:
      enabled: true
    telemetry:
      enabled: false
  values:
    sidecarInjectorWebhook:
      rewriteAppHTTPProbe: true
    gateways:
      istio-ingressgateway:
        serviceAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
          service.beta.kubernetes.io/aws-load-balancer-internal: "true"
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
          external-dns.alpha.kubernetes.io/hostname: kiali.kimdragon50.ml, web.kimdragon50.ml, emp.kimdragon50.ml
    global:
      defaultNodeSelector:
        nodegroup-type: MANAGE
      configValidation: false
      proxy:
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"