apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prometheus-virtualservice
  namespace: prometheus
spec:
  gateways:
  - prometheus-gateway
  hosts:
  - "prometheus.kimdragon50.ml"
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: prometheus-server
        port:
          number: 80